### ISSUE TITLE
Feature request: EL-Chat Generative AI integration effort (est. effort: 1-2 days)

### ISSUE THREAD

**Issue by everylisting** [Yana-Gupta/real-estate-frontend#1]
Hi,

I am the creator of EL-Chat (https://youtu.be/FV-WBR50sKA) and would love to work with you to enable the codebase to interface with it. We are javascript-ready (we just need to setup a couple of routines to pull the properties) for the code to become entirely Generative AI enabled.

Could we work together on this?

Philippe Roy
proy@everylisting.com

**Comment by Yana-Gupta** [comment]
Hi @everylisting 

Thanks for reaching out, and for your interest in integrating Generative AI capabilities into EL-Chat. 
While I am unable to undertake much coding work now, but I will be very much happy if you I can assist you in many other way. You can sure add the requested feature here. I will sure assist you.

Thanks
