### ISSUE TITLE
[CHORE] Ensure responsiveness of the search across various tab sizes

### ISSUE THREAD

**Issue by Yana-Gupta** [Yana-Gupta/real-estate-frontend#14]
Ensure and maintain the responsiveness of this search bar on various screen sizes. Currently at some viewpoints its responsiveness is breaking. 

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/103108630/e068d2b9-a863-4d97-9e6a-79325c8a78e1)

You have to make sure that this search bar is responsive on various screens.

**Comment by shubhampr07** [comment]
Hey Yana, can you assign this to me.

**Comment by Yana-Gupta** [comment]
Sure @shubhampr07, assigning to you
