### ISSUE TITLE
[BUG] Change the color of button

### ISSUE THREAD

**Issue by Yana-Gupta** [Yana-Gupta/real-estate-frontend#15]
Change the color of the button to other color while hovering in menu bar: 

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/103108630/823b7e96-f5bb-4232-b0d1-b0f05367a651)

You can use some other shade of blue of color, to improve UI

**Comment by Chetax** [comment]
i want to solve this issue can you assign it to me please

**Comment by Yana-Gupta** [comment]
Sure @Chetax Go ahead 🚀

**Comment by Priyadarshani7** [comment]
Is this issue solved ? If not can you assign it to me..

**Comment by Yana-Gupta** [comment]
@Priyadarshani7 Let's wait for the update from @Chetax

**Comment by Yana-Gupta** [comment]
@Priyadarshani7 since no activities are from @Chetax, so assigned to you

**Comment by Yana-Gupta** [comment]
@Chetax are you still working on this issue.

**Comment by Chetax** [comment]
Sorry @Yana-Gupta i am not working on this issue.

**Comment by Yana-Gupta** [comment]
@Priyadarshani7 ?

**Comment by tharanithar-r** [comment]
I am interested in solving this bug. Can you assign it to me?

**Comment by Yana-Gupta** [comment]
Sure @tharanithar-r
