### ISSUE TITLE
Improve the load time of image in home page

### ISSUE THREAD

**Issue by Yana-Gupta** [Yana-Gupta/real-estate-frontend#16]
Ensure to decrease the rendering time of the image, as it looks unresponsive 

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/103108630/801a80e8-d865-4106-8f58-c5a185775500)

**Comment by theDevSoham** [comment]
Hello @Yana-Gupta if you need help with image optimization I have some ideas to try on this area, could you please assign me this task?

**Comment by Yana-Gupta** [comment]
Sure @theDevSoham, assigned to you 👍🏼

**Comment by Yana-Gupta** [comment]
Please comment the ideas when you make a **PR**
