### ISSUE TITLE
Improve the design while opening ham menu

### ISSUE THREAD

**Issue by Yana-Gupta** [Yana-Gupta/real-estate-frontend#17]
Improve the design while opening ham menu.

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/103108630/1fc2da4f-5d95-4f16-b1a3-537d27f1c916)

The current design is simple.. If would be nice to some other design in place of it. 

**P.S** Please share the images / video after making a **PR**

**Comment by SoldierCorp** [comment]
Hi @Yana-Gupta 

I would like to contribute to your project. Could you please assign this task to me?

**Comment by Yana-Gupta** [comment]
Sounds good @SoldierCorp assigned to you

**Comment by veerendra19codes** [comment]
is this issue still open i can add some hover effects on this.can you assign this issue to me @Yana-Gupta

**Comment by Yana-Gupta** [comment]
@veerendra19codes sure

**Comment by veerendra19codes** [comment]
thank you for assigning i m working on it now

**Comment by veerendra19codes** [comment]
@Yana-Gupta Please review my PR✌️🥰

**Comment by Akshada-26** [comment]
Please assign it to me

**Comment by Akshada-26** [comment]
I have edited and changed the titles of the hamp menu

**Comment by Chetax** [comment]
@Yana-Gupta Does @Akshada-26 Is Still Working On this Issue Else Assign To Me
