### ISSUE TITLE
Signup page not opening from sign-in page

### ISSUE THREAD

**Issue by Laxmankohar** [Yana-Gupta/real-estate-frontend#23]
It is only showing the blank page.

**Comment by Yana-Gupta** [comment]
I don't think such error exists... Please check again and if happening share screenshots.

**Comment by Laxmankohar** [comment]
first click on sign-in button at

**Comment by Laxmankohar** [comment]
first click on sign-in button at the top and after that click on sign-up button inside sign in page, it will only show blank page

**Comment by Yana-Gupta** [comment]
Got it. Do you want to fix it

**Comment by Laxmankohar** [comment]
Yes

**Comment by Yana-Gupta** [comment]
Here you go 🚀
