### ISSUE TITLE
Enhancement Request: Beautify Login and Sign-Up Pages

### ISSUE THREAD

**Issue by Laxmankohar** [Yana-Gupta/real-estate-frontend#24]
The login and signup page can be enhanced more in a beautiful way.

**Comment by Laxmankohar** [comment]
Could you assign me this issue ?

**Comment by Yana-Gupta** [comment]
Sure @Laxmankohar

**Comment by Laxmankohar** [comment]
@Yana-Gupta , Can you please check it?

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/3fd2a40a-6dcb-4d4b-81d0-4d4e838e2e7c)
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/8ea89af3-1a20-4116-93dd-5b8f3fb1dfb7)

**Comment by Yana-Gupta** [comment]
I will suggest making background of the page better then accordingly fix the card's color. 
Thanks for your work but I will suggest some other design if you can.

**Comment by Laxmankohar** [comment]
OK

**Comment by Laxmankohar** [comment]
@Yana-Gupta , Check this color combination.

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/92404f96-5e49-415c-9fb0-68849b701079)

**Comment by Yana-Gupta** [comment]
Well I didn't like the color you are using try to go for some dark bluish shade and to make it look better you can add opacity to it.. 
Then some gradient if you want to.

Rest I appreciate your hard work 👏🏼

**Comment by Laxmankohar** [comment]
@Yana-Gupta ,Now check this. if it is not good , i will to try to enhance it more.

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/f3851752-bf25-4399-90c2-78534e0d79f8)

**Comment by Yana-Gupta** [comment]
Try with this color `45585E` and add `opacity` css property as per need .. sorry this one doesn't satisfied me

**Comment by Laxmankohar** [comment]
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/daf99487-5a21-4b18-ad46-5eb30d5a1d2b)

**Comment by Yana-Gupta** [comment]
Please make changes on signup page.. login page looks fine to me.. also add `opacity` property of css. You can lean more about how to implement it [here](https://www.w3schools.com/cssref/css3_pr_opacity.php) 

I'm not saying make it completely invisible.. but the background looks good due to it.

**Comment by Laxmankohar** [comment]
@Yana-Gupta , Now check it

![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/2b5c7e17-60fb-4740-bb56-ee57df06f62d)
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/65546830-196a-4db9-ad53-0b1c04f964c7)

**Comment by Yana-Gupta** [comment]
Don't make changes on login page please and keep the card color to white .. rest it's fine .. if you can decrease the opacity and make it more light, rest it's fine make a pr

**Comment by Laxmankohar** [comment]
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/dd5b9463-2ad0-4994-a1f1-7539521baabc)
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/735dd6e2-1cbe-43ec-a402-57599306da77)

**Comment by Yana-Gupta** [comment]
Why are you making changes on Login page and and give shadow to the card on signup page, also don't add opacity to the card on signup page.

**Comment by Laxmankohar** [comment]
i should  make login page card a white color and  don't need to use opacity and in signup page , i need to use white color with some shadow  to the card

**Comment by Yana-Gupta** [comment]
@Laxmankohar please use some better techniques to style changing `backgroundColor` even if it is not looking good is not considered as a better style. There are so many different approach you can use them.

**Comment by Laxmankohar** [comment]
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/ff09415e-2e0c-40ba-9936-a6f3a4b7687f)

**Comment by Yana-Gupta** [comment]
Sure. Make a pr

**Comment by Yana-Gupta** [comment]
Thanks but you may take other issues
