### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by Laxmankohar** [Yana-Gupta/real-estate-frontend#25]
Having a favicon makes your website look more professional.

**Comment by Laxmankohar** [comment]
I would like to work on this issue.Could you please assign it to me?

**Comment by Yana-Gupta** [comment]
Then you have to first create the favicon... if you want you can..
Assigned to you 💯

**Comment by Laxmankohar** [comment]
@Yana-Gupta , Check this favicon. Is it ok?

![favicon-32x32](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/84878d50-2855-4386-ae80-885dddb24ae6)

**Comment by Yana-Gupta** [comment]
Thanks @Laxmankohar the favicon is nice.. but I request you to add some space horizontally ow its 💯

**Comment by Laxmankohar** [comment]
![image](https://github.com/Yana-Gupta/real-estate-frontend/assets/73365025/dac1024b-0c79-4b43-b260-41ba74e0a34a)

**Comment by Yana-Gupta** [comment]
I thing it should be RE instead of FE, plus reduce some space if you can. rest its fine.. you can create a PR for this

**Comment by Laxmankohar** [comment]
ok
