### ISSUE TITLE
Improve Sign-In and Sign-Up Button

### ISSUE THREAD

**Issue by Mayank-Sharma17** [Yana-Gupta/real-estate-frontend#34]
I'd like to improve the sign-in and sign-up buttons in the navigation bar, and as we reduce the width of the viewport, the width of the buttons similarly decreases.

![Screenshot 2023-10-13 002723](https://github.com/Yana-Gupta/real-estate-frontend/assets/113251342/61a10eb1-a5de-4e1f-a42c-ea520f20d225)

**Comment by Yana-Gupta** [comment]
Sure, Go ahead @Mayank-Sharma17 🚀
